### PR TITLE
tutorial bayes opt

### PR DESCRIPTION
**Pull request by FredericRapp**
solves #118

### CODE REVIEW

**Review by rothma — CHANGES_REQUESTED** [review]
Rename bayesian_optimization_with_qgpr.ipynb -> quantum_bayesian_optimization.ipynb

**Comment by rothma** [comment]
Fig 1: add reference to paper

**Comment by rothma** [comment]
Otherwise I like it a lot. After you address the two comments, you are good to merge.

**Comment by rothma** [comment]
Oh, one more request: Please link the tutorial in the documentation. You can follow the example in the docs/examples folder.

**Comment by FredericRapp** [comment]
done, but please check real quick @rothma

**Review by rothma — APPROVED** [review]

**Pull request merged**
