### PR TITLE
Add get_params() and set_params() to QKRR

### PR DESCRIPTION
**Pull request by JanSchnabel**
* Can't set "gamma" parameter when using "gaussian" outer_kernel in PQK => didn't manage to fix this
* Modified FQK such that evaluate_duplicates and mit_depol_noise is also returned from get_params(deep=True) -> not sure if we really want this?
* Do we want to include the regularization parameter into getters and setters?

### CODE REVIEW

**Comment by David-Kreplin** [comment]
> * Modified FQK such that evaluate_duplicates and mit_depol_noise is also returned from get_params(deep=True) -> not sure if we really want this?

Thanks for fixing that, forgot about that issue

**Comment by David-Kreplin** [comment]
> * Can't set "gamma" parameter when using "gaussian" outer_kernel in PQK => didn't manage to fix this

very strange, I will take a look.

**Comment by JanSchnabel** [comment]
> 

Yes, exactly. I can take care of this

**Review by David-Kreplin — APPROVED** [review]
kwargs, set_params and get_params now working

**Pull request merged**
